
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    400.0,
    fill="#275199",
    outline="")

canvas.create_text(
    116.0,
    168.0,
    anchor="nw",
    text="Input your best email and receive your video",
    fill="#FFFFFF",
    font=("Inter", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    399.5,
    288.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F0F0F0",
    highlightthickness=0
)
entry_1.place(
    x=211.5,
    y=260.0,
    width=376.0,
    height=55.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=212.0,
    y=259.0,
    width=410.0,
    height=58.0
)

canvas.create_text(
    238.0,
    83.0,
    anchor="nw",
    text="ALL DONE!",
    fill="#FFFFFF",
    font=("JollyLodger", 105 * -1)
)
window.resizable(False, False)
window.mainloop()
