
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x400")
window.configure(bg = "#48D34E")


canvas = Canvas(
    window,
    bg = "#48D34E",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("letsgo.png"))
image_1 = canvas.create_image(
    400.0,
    175.0,
    image=image_image_1
)

canvas.create_text(
    300.0,
    75.0,
    anchor="nw",
    text="LET’S \nGO!!!",
    fill="#000000",
    font=("JollyLodger", 120 * -1)
)
window.resizable(False, False)
window.mainloop()
